[package]
name = "rust_chess"
version = "0.1.0"
authors = ["Matt <Matthew.ord1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ux = "0.1.3"